# Generated by Django 5.2.17 on 2026-09-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('extension_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('developer', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('rating_value', models.FloatField(blank=True, null=True)),
                ('rating_count', models.BigIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('extension_rank', models.BigIntegerField(blank=True, null=True)),
                ('overall_rank', models.BigIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extension',
            },
        ),
        migrations.CreateModel(
            name='ExtensionChart',
            fields=[
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chart', serialize=False, to='intelligence.extension')),
                ('history', models.JSONField(default=list)),
                ('milestones', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extension_chart',
            },
        ),
        migrations.CreateModel(
            name='ExtensionMetric',
            fields=[
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metric', serialize=False, to='intelligence.extension')),
                ('user_count', models.BigIntegerField(blank=True, null=True)),
                ('user_count_change_1d', models.BigIntegerField(blank=True, null=True)),
                ('user_count_change_7d', models.BigIntegerField(blank=True, null=True)),
                ('user_count_change_30d', models.BigIntegerField(blank=True, null=True)),
                ('user_growth_rate_1d', models.FloatField(blank=True, null=True)),
                ('user_growth_rate_7d', models.FloatField(blank=True, null=True)),
                ('user_growth_rate_30d', models.FloatField(blank=True, null=True)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('days_since_update', models.IntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extension_metric',
            },
        ),
    ]
