# Generated by Django 5.2.17 on 2026-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionmetric',
            name='user_count_growth_acceleration_7d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
