# Generated by Django 5.2.17 on 2026-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_extensionmetric_user_count_growth_acceleration_7d'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
