# Generated by Django 5.2.17 on 2026-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_researchrequest_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='extension',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
