# Generated by Django 5.2.17 on 2026-09-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_userprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionmetric',
            name='date_to_1000',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='date_to_10000',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='date_to_100000',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='date_to_3000',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='date_to_30000',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='days_to_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='days_to_10000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='days_to_100000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='days_to_3000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='days_to_30000',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
