# Generated by Django 5.2.17 on 2026-09-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_extensionmetric_date_to_1000_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
