# Generated by Django 5.2.17 on 2026-09-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_userprofile_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='by_google',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='is_trusted_publisher',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
