# Generated by Django 5.2.17 on 2026-09-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_extension_by_google_extension_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='extension',
            name='is_unlisted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='seo_qualify_streak_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='seo_tier',
            field=models.CharField(choices=[('candidate', '候选（观察中）'), ('tier1', 'Tier 1（已索引）'), ('tier1_grace', 'Tier 1 宽限期（仍索引）'), ('excluded', '已排除（noindex）')], db_index=True, default='candidate', max_length=16),
        ),
        migrations.AddField(
            model_name='extension',
            name='seo_tier_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='user_count_change_90d',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionmetric',
            name='user_growth_rate_90d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='extensionmetric',
            name='age_days',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionmetric',
            name='user_count',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionmetric',
            name='user_count_change_30d',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionmetric',
            name='user_count_change_7d',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionmetric',
            name='user_count_growth_acceleration_7d',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionmetric',
            name='user_growth_rate_30d',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
