# Generated by Django 5.2.17 on 2026-09-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0010_extension_description_extension_is_unlisted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='seo_tier',
            field=models.CharField(choices=[('candidate', '候选（观察中）'), ('tier1', 'Tier 1（已索引）'), ('tier1_grace', 'Tier 1 宽限期（仍索引）'), ('excluded', '已排除（noindex）')], db_default='candidate', db_index=True, default='candidate', max_length=16),
        ),
    ]
