# Generated by Django 5.2.17 on 2026-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0011_alter_extension_seo_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='seo_tier',
            field=models.CharField(choices=[('candidate', 'Candidate (observing)'), ('tier1', 'Tier 1 (indexed)'), ('tier1_grace', 'Tier 1 grace period (still indexed)'), ('excluded', 'Excluded (noindex)')], db_default='candidate', db_index=True, default='candidate', max_length=16),
        ),
        migrations.AlterField(
            model_name='researchrequest',
            name='output_format',
            field=models.CharField(choices=[('CSV', 'CSV'), ('Excel', 'Excel'), ('PDF', 'PDF Report')], default='CSV', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional ($499/mo)'), ('custom', 'Custom Intelligence ($1,499/mo)')], default='free', max_length=20),
        ),
    ]
